---
- name: utility.example.com
  provider: vmware_desktop
  box: rhel-8.4-graph-vmware
  ssh: 2222
  cpus: 2
  memory: 2048
  dvds:
    - name: redhat-iso
      path: /ISO
      file: /ISO/rhel-8.4-x86_64-dvd.iso
  disks:
    - name: vdo1
      size: 20480        
    - name: nfs
      size: 5120 
  networks:
    - interface: private_network
      type: static
      ip: 192.168.14.100
      gateway: 192.168.14.1
      hostname: true
- name: acontroller.example.com
  provider: vmware_desktop
  box: rhel-8.4-graph-vmware
  ssh: 2222
  cpus: 2
  memory: 2048
  networks:
    - interface: private_network
      type: static
      ip: 192.168.14.101
      gateway: 192.168.14.1
      hostname: true
- name: ansible1.example.com
  provider: vmware_desktop
  box: rhel-8.4-graph-vmware
  ssh: 2222
  cpus: 2
  memory: 2048
  disks:
    - name: vdo1
      size: 5120
  networks:
    - interface: private_network
      type: static
      ip: 192.168.14.120
      gateway: 192.168.14.1
      hostname: true
- name: ansible2.example.com
  provider: vmware_desktop
  box: rhel-8.4-text-vmware
  ssh: 2222
  cpus: 2
  memory: 1024
  disks:
    - name: vdo1
      size: 5120
  networks:
    - interface: private_network
      type: static
      ip: 192.168.14.121
      gateway: 192.168.14.1
      hostname: true
- name: rhel84-std-1
  provider: vmware_desktop
  box: rhel-8.4-text-vmware
  ssh: 2222
  cpus: 2
  memory: 1024
  disks:
    - name: vdo1
      size: 5120
    - name: vdo2
      size: 5120
  networks:
    - interface: private_network
      type: static
      ip: 192.168.14.110
      gateway: 192.168.14.1
      hostname: true
- name: rhel84-std-2
  provider: vmware_desktop
  box: rhel-8.4-graph-vmware
  ssh: 2222
  cpus: 2
  memory: 2048
  disks:
    - name: vdo1
      size: 5120
    - name: vdo2
      size: 5120
  networks:
    - interface: private_network
      type: static
      ip: 192.168.14.111
      gateway: 192.168.14.1
      hostname: true
