## Common ###
  rhel_mode = "text"
  rhel_version = "8.4"
  rhel_architechture = "x86_64"
  rhel_media = "-dvd"
  http_bind_address="192.168.14.1"
  vb_http_bind_address="192.168.1.92"
  http_directory="http"
  iso_checksum="md5:40ed634c160258a1fce05f525455a473"
  ssh_username="root"
  ssh_password="password"
  ssh_timeout="10m"
  boot_wait="5s"
  headless="false"
  cpus="2"
  memory="1024"
  disk_size="20480"
  shutdown_command="shutdown -P now"
  vb_shutdown_command="shutdown -P now"
  usb = "false"
  output_directory = "packer_out"
  output_box_directory = "box_out"
## End common ##

## vmware-iso specifics
  sound="false"
  vmx_remove_ethernet_interfaces = "true"
  core="1"
  disk_type_id="0"
  network="nat"

## virtualbox-iso specifics
  chipset="ich9"
  firmware="bios"
  nested_virt="on"
  rtc_time_base="on"
  nic_type="82540em"
  audio_controller="ac97"
  gfx_controller="vmsvga"
  gfx_vram_size="16"
  gfx_accelerate_3d="false"
  vb_guest_os_type = "RedHat_64"
  hard_drive_discard="true"
  hard_drive_interface="sata"
  sata_port_count="1"
  nvme_port_count="0"
  hard_drive_nonrotational="true"
  iso_interface="sata"
  bundle_iso="false"
  guest_additions_mode="attach"
  guest_additions_interface=""
#  guest_additions_path="/opt/VBoxGuestAdditions.iso"
  guest_additions_path=""
  guest_additions_sha256="bffc316a7b8d5ed56d830e9f6aef02b4e5ffc28674032142e96ffbedd905f8c9"
  guest_additions_url="file:///ISO/VBoxGuestAdditions.iso"
  format="ovf"
  vbsound = "none"
  skip_nat_mapping="true"
  vb_network="nat"
  

## Post-processor variables
post_vmware_compression_level="8"
